# Enable this if you want the durability to be reduced for each broken block
useDurabilityPerBlock: false

# These define the blocks that can be mined by the hammer, and which quality of base pickaxe is needed
# (these are set according to the information on the minecraft wiki)
Minable:
 - COBBLESTONE: [any]
 - STONE: [any]
 - GRANITE: [any]
 - POLISHED_GRANITE: [any]
 - DIORITE: [any]
 - POLISHED_DIORITE: [any]
 - ANDESITE: [any]
 - POLISHED_ANDESITE: [any]
 - BRICKS: [any]
 - MOSSY_COBBLESTONE: [any]
 - COAL_ORE: [any]
 - SANDSTONE: [any]
 - END_STONE: [any]
 - NETHERRACK: [any]
 - NETHER_BRICKS: [any]
 - NETHER_QUARTZ_ORE: [any]
 - WHITE_TERRACOTTA: [any]
 - ORANGE_TERRACOTTA: [any]
 - MAGENTA_TERRACOTTA: [any]
 - LIGHT_BLUE_TERRACOTTA: [any]
 - YELLOW_TERRACOTTA: [any]
 - LIME_TERRACOTTA: [any]
 - PINK_TERRACOTTA: [any]
 - GRAY_TERRACOTTA: [any]
 - LIGHT_GRAY_TERRACOTTA: [any]
 - CYAN_TERRACOTTA: [any]
 - PURPLE_TERRACOTTA: [any]
 - BLUE_TERRACOTTA: [any]
 - BROWN_TERRACOTTA: [any]
 - GREEN_TERRACOTTA: [any]
 - RED_TERRACOTTA: [any]
 - BLACK_TERRACOTTA: [any]
 - TERRACOTTA: [any]
 - GLOWSTONE: [any]
 - OBSIDIAN: [DIAMOND_PICKAXE]
 - REDSTONE_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE]
 - GLOWING_REDSTONE_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE]
 - GOLD_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE]
 - DIAMOND_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE]
 - EMERALD_ORE: [IRON_PICKAXE, DIAMOND_PICKAXE]
 - LAPIS_ORE: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE]
 - IRON_ORE: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE]
# - COAL_BLOCK: [any]
# - REDSTONE_BLOCK: [any]
# - QUARTZ_BLOCK: [any]
# - LAPIS_BLOCK: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE]
# - IRON_BLOCK: [STONE_PICKAXE, IRON_PICKAXE, DIAMOND_PICKAXE]
# - GOLD_BLOCK: [IRON_PICKAXE, DIAMOND_PICKAXE]
# - DIAMOND_BLOCK: [IRON_PICKAXE, DIAMOND_PICKAXE]
# - EMERALD_BLOCK: [IRON_PICKAXE, DIAMOND_PICKAXE]

# These define the blocks that can be dug by the excavator
Diggable:
 - GRASS_BLOCK
 - DIRT
 - COARSE_DIRT
 - PODZOL
 - SAND
 - RED_SAND
 - GRAVEL
 - CLAY
 - SOUL_SAND
 - SNOW_BLOCK
 - SNOW
 - MYCELIUM
 - FARMLAND
 - GLOWSTONE
